title: Bowen Li
description: Data Scitist & Algorithm Engineer
site_title: ''

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: crazybruce-bowen
email: libowenking@126.com

# absolute or relative
profile_picture: assets/images/life1.jpg
